apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: podinfo-test
  namespace: demo
spec:
  meshName: aws-eks-appmesh-cloudmap-demo
  listeners:
    - portMapping:
        port: 9898
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: demo-http
      serviceName: podinfo
  logging:
    accessLog:
      file:
        path: /dev/stdout
